// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package dep

import (
	"database/sql"

	"github.com/google/wire"
	"github.com/short-d/app/fw"
	"github.com/short-d/app/modern/mdcli"
	"github.com/short-d/app/modern/mddb"
	"github.com/short-d/app/modern/mdenv"
	"github.com/short-d/app/modern/mdgrpc"
	"github.com/short-d/app/modern/mdio"
	"github.com/short-d/app/modern/mdlogger"
	"github.com/short-d/app/modern/mdruntime"
	"github.com/short-d/app/modern/mdservice"
	"github.com/short-d/app/modern/mdtimer"
	"github.com/short-d/app/modern/mdtracer"
	"github.com/short-d/kgs/app/adapter/db"
	"github.com/short-d/kgs/app/adapter/rpc"
	"github.com/short-d/kgs/app/usecase"
	"github.com/short-d/kgs/app/usecase/dispatcher"
	"github.com/short-d/kgs/app/usecase/keys"
	"github.com/short-d/kgs/app/usecase/keys/gen"
	"github.com/short-d/kgs/dep/provider"
)

// Injectors from wire.go:

func InitCommandFactory() fw.CommandFactory {
	cobraFactory := mdcli.NewCobraFactory()
	return cobraFactory
}

func InitDBConnector() fw.DBConnector {
	postgresConnector := mddb.NewPostgresConnector()
	return postgresConnector
}

func InitDBMigrationTool() fw.DBMigrationTool {
	postgresMigrationTool := mddb.NewPostgresMigrationTool()
	return postgresMigrationTool
}

func InitEnvironment() fw.Environment {
	goDotEnv := mdenv.NewGoDotEnv()
	return goDotEnv
}

func InitGRpcService(name string, logLevel fw.LogLevel, serviceEmailAddress provider.ServiceEmailAddress, sqlDB *sql.DB, securityPolicy fw.SecurityPolicy, sendGridAPIKey provider.SendGridAPIKey, templateRootDir provider.TemplateRootDir, cacheSize provider.CacheSize, eventDispatcher fw.Dispatcher) (mdservice.Service, error) {
	stdOut := mdio.NewBuildInStdOut()
	timer := mdtimer.NewTimer()
	buildIn := mdruntime.NewBuildIn()
	local := mdlogger.NewLocal(name, logLevel, stdOut, timer, buildIn)
	availableKeySQL := db.NewAvailableKeySQL(sqlDB)
	v := gen.NewBase62()
	alphabet, err := gen.NewAlphabet(v)
	if err != nil {
		return mdservice.Service{}, err
	}
	producerPersist := keys.NewProducerPersist(availableKeySQL, alphabet, local)
	allocatedKeySQL := db.NewAllocatedKeySQL(sqlDB)
	consumerPersist := keys.NewConsumerPersist(availableKeySQL, allocatedKeySQL)
	consumerCached, err := provider.NewConsumer(cacheSize, consumerPersist)
	if err != nil {
		return mdservice.Service{}, err
	}
	template := provider.NewHTML(templateRootDir)
	sendGrid := provider.NewSendGrid(sendGridAPIKey)
	emailNotifierEventListener := provider.NewEmailNotifierEventListener(local, template, name, serviceEmailAddress, sendGrid)
	emitter, err := dispatcher.NewEventEmitter(eventDispatcher, emailNotifierEventListener)
	if err != nil {
		return mdservice.Service{}, err
	}
	useCase := usecase.NewUseCase(local, producerPersist, consumerCached, emitter)
	keyGenServer := rpc.NewKeyGenServer(useCase)
	kgsAPI := rpc.NewKgsAPI(keyGenServer)
	gRpc, err := mdgrpc.NewGRpc(kgsAPI, securityPolicy)
	if err != nil {
		return mdservice.Service{}, err
	}
	service := mdservice.New(name, gRpc, local)
	return service, nil
}

// wire.go:

var observabilitySet = wire.NewSet(wire.Bind(new(fw.Logger), new(mdlogger.Local)), mdlogger.NewLocal, mdtracer.NewLocal)
