// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package dep

import (
	"database/sql"
	"errors"
	"github.com/byliuyang/app/fw"
	"github.com/byliuyang/app/modern/mdcli"
	"github.com/byliuyang/app/modern/mddb"
	"github.com/byliuyang/app/modern/mdenv"
	"github.com/byliuyang/app/modern/mdgrpc"
	"github.com/byliuyang/app/modern/mdlogger"
	"github.com/byliuyang/app/modern/mdservice"
	"github.com/byliuyang/app/modern/mdtracer"
	"github.com/byliuyang/kgs/app/adapter/db"
	"github.com/byliuyang/kgs/app/adapter/rpc"
	"github.com/byliuyang/kgs/app/usecase/keys"
	"github.com/byliuyang/kgs/app/usecase/keys/gen"
	"github.com/byliuyang/kgs/app/usecase/repo"
	"github.com/byliuyang/kgs/app/usecase/transactional"
	"github.com/byliuyang/kgs/dep/provider"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitCommandFactory() fw.CommandFactory {
	cobraFactory := mdcli.NewCobraFactory()
	return cobraFactory
}

func InitDBConnector() fw.DBConnector {
	postgresConnector := mddb.NewPostgresConnector()
	return postgresConnector
}

func InitDBMigrationTool() fw.DBMigrationTool {
	postgresMigrationTool := mddb.NewPostgresMigrationTool()
	return postgresMigrationTool
}

func InitEnvironment() fw.Environment {
	goDotEnv := mdenv.NewGoDotEnv()
	return goDotEnv
}

func InitGRpcService(name string, serviceEmailAddress provider.ServiceEmailAddress, sqlDB *sql.DB, securityPolicy fw.SecurityPolicy, sendGridAPIKey provider.SendGridAPIKey, templatePattern provider.TemplatePattern, cacheSize provider.CacheSize) (mdservice.Service, error) {
	availableKeySQL := db.NewAvailableKeySQL(sqlDB)
	v := gen.NewBase62()
	alphabet, err := gen.NewAlphabet(v)
	if err != nil {
		return mdservice.Service{}, err
	}
	logger := mdlogger.NewLocal()
	producerPersist := keys.NewProducerPersist(availableKeySQL, alphabet, logger)
	availableKeyRepoFactory := availableKey()
	allocatedKeyRepoFactory := allocatedKey()
	factorySQL := db.NewFactorySQL(sqlDB)
	consumerPersist := keys.NewConsumerPersist(availableKeyRepoFactory, allocatedKeyRepoFactory, factorySQL)
	consumerCached, err := provider.NewConsumer(cacheSize, consumerPersist)
	if err != nil {
		return mdservice.Service{}, err
	}
	sendGrid := provider.NewSendGrid(sendGridAPIKey)
	emailNotifier := provider.NewEmailNotifier(name, serviceEmailAddress, sendGrid)
	template, err := provider.NewTemplate(templatePattern)
	if err != nil {
		return mdservice.Service{}, err
	}
	keyGenServer := rpc.NewKeyGenServer(producerPersist, consumerCached, emailNotifier, template, logger)
	kgsAPI := rpc.NewKgsAPI(keyGenServer)
	gRpc, err := mdgrpc.NewGRpc(kgsAPI, securityPolicy)
	if err != nil {
		return mdservice.Service{}, err
	}
	service := mdservice.New(name, gRpc, logger)
	return service, nil
}

// wire.go:

func allocatedKey() keys.AllocatedKeyRepoFactory {
	return func(tx transactional.Transaction) (repo.AllocatedKey, error) {
		sqlTx, ok := tx.(*sql.Tx)

		if !ok {
			return nil, errors.New("allocatedKeyFactory expects sql.Tx")
		}

		return db.NewAllocatedKeyTransactional(sqlTx), nil
	}
}

func availableKey() keys.AvailableKeyRepoFactory {
	return func(tx transactional.Transaction) (repo.AvailableKey, error) {
		sqlTx, ok := tx.(*sql.Tx)

		if !ok {
			return nil, errors.New("availableKeyFactory expects sql.Tx")
		}

		return db.NewAvailableKeyTransactional(sqlTx), nil
	}
}

var observabilitySet = wire.NewSet(mdlogger.NewLocal, mdtracer.NewLocal)
