// Code generated by protoc-gen-go. DO NOT EDIT.
// source: app/adapter/rpc/proto/kgs.proto

package proto

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PopulateKeysRequest struct {
	KeyLength            uint32   `protobuf:"varint,1,opt,name=key_length,json=keyLength,proto3" json:"key_length,omitempty"`
	RequesterEmail       string   `protobuf:"bytes,2,opt,name=requester_email,json=requesterEmail,proto3" json:"requester_email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PopulateKeysRequest) Reset()         { *m = PopulateKeysRequest{} }
func (m *PopulateKeysRequest) String() string { return proto.CompactTextString(m) }
func (*PopulateKeysRequest) ProtoMessage()    {}
func (*PopulateKeysRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_560181f7f28564fe, []int{0}
}

func (m *PopulateKeysRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PopulateKeysRequest.Unmarshal(m, b)
}
func (m *PopulateKeysRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PopulateKeysRequest.Marshal(b, m, deterministic)
}
func (m *PopulateKeysRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PopulateKeysRequest.Merge(m, src)
}
func (m *PopulateKeysRequest) XXX_Size() int {
	return xxx_messageInfo_PopulateKeysRequest.Size(m)
}
func (m *PopulateKeysRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PopulateKeysRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PopulateKeysRequest proto.InternalMessageInfo

func (m *PopulateKeysRequest) GetKeyLength() uint32 {
	if m != nil {
		return m.KeyLength
	}
	return 0
}

func (m *PopulateKeysRequest) GetRequesterEmail() string {
	if m != nil {
		return m.RequesterEmail
	}
	return ""
}

type AllocateKeysRequest struct {
	MaxKeyCount          uint32   `protobuf:"varint,1,opt,name=max_key_count,json=maxKeyCount,proto3" json:"max_key_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AllocateKeysRequest) Reset()         { *m = AllocateKeysRequest{} }
func (m *AllocateKeysRequest) String() string { return proto.CompactTextString(m) }
func (*AllocateKeysRequest) ProtoMessage()    {}
func (*AllocateKeysRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_560181f7f28564fe, []int{1}
}

func (m *AllocateKeysRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllocateKeysRequest.Unmarshal(m, b)
}
func (m *AllocateKeysRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllocateKeysRequest.Marshal(b, m, deterministic)
}
func (m *AllocateKeysRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllocateKeysRequest.Merge(m, src)
}
func (m *AllocateKeysRequest) XXX_Size() int {
	return xxx_messageInfo_AllocateKeysRequest.Size(m)
}
func (m *AllocateKeysRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AllocateKeysRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AllocateKeysRequest proto.InternalMessageInfo

func (m *AllocateKeysRequest) GetMaxKeyCount() uint32 {
	if m != nil {
		return m.MaxKeyCount
	}
	return 0
}

type AllocateKeysResponse struct {
	Keys                 []string `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AllocateKeysResponse) Reset()         { *m = AllocateKeysResponse{} }
func (m *AllocateKeysResponse) String() string { return proto.CompactTextString(m) }
func (*AllocateKeysResponse) ProtoMessage()    {}
func (*AllocateKeysResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_560181f7f28564fe, []int{2}
}

func (m *AllocateKeysResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllocateKeysResponse.Unmarshal(m, b)
}
func (m *AllocateKeysResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllocateKeysResponse.Marshal(b, m, deterministic)
}
func (m *AllocateKeysResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllocateKeysResponse.Merge(m, src)
}
func (m *AllocateKeysResponse) XXX_Size() int {
	return xxx_messageInfo_AllocateKeysResponse.Size(m)
}
func (m *AllocateKeysResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AllocateKeysResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AllocateKeysResponse proto.InternalMessageInfo

func (m *AllocateKeysResponse) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

func init() {
	proto.RegisterType((*PopulateKeysRequest)(nil), "proto.PopulateKeysRequest")
	proto.RegisterType((*AllocateKeysRequest)(nil), "proto.AllocateKeysRequest")
	proto.RegisterType((*AllocateKeysResponse)(nil), "proto.AllocateKeysResponse")
}

func init() { proto.RegisterFile("app/adapter/rpc/proto/kgs.proto", fileDescriptor_560181f7f28564fe) }

var fileDescriptor_560181f7f28564fe = []byte{
	// 275 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x50, 0x4d, 0x4b, 0xc4, 0x30,
	0x14, 0xa4, 0x7e, 0x2c, 0xf4, 0xb9, 0xab, 0x90, 0x15, 0x29, 0x5d, 0xc4, 0xd2, 0x8b, 0xc5, 0x43,
	0x0b, 0x7a, 0xf2, 0xa8, 0xb2, 0xec, 0xa1, 0x1e, 0xa4, 0x77, 0x29, 0xd9, 0xfa, 0xac, 0xd2, 0xb4,
	0x89, 0x49, 0x0a, 0x9b, 0x1f, 0xe2, 0xff, 0x95, 0x26, 0xba, 0xac, 0x4b, 0x4f, 0x79, 0xcc, 0xbc,
	0xcc, 0xbc, 0x19, 0xb8, 0xa2, 0x42, 0x64, 0xf4, 0x8d, 0x0a, 0x8d, 0x32, 0x93, 0xa2, 0xca, 0x84,
	0xe4, 0x9a, 0x67, 0x4d, 0xad, 0x52, 0x3b, 0x91, 0x63, 0xfb, 0x84, 0x8b, 0x9a, 0xf3, 0x9a, 0xa1,
	0xa3, 0xd7, 0xfd, 0x7b, 0x86, 0xad, 0xd0, 0xc6, 0xed, 0xc4, 0xaf, 0x30, 0x7f, 0xe1, 0xa2, 0x67,
	0x54, 0x63, 0x8e, 0x46, 0x15, 0xf8, 0xd5, 0xa3, 0xd2, 0xe4, 0x12, 0xa0, 0x41, 0x53, 0x32, 0xec,
	0x6a, 0xfd, 0x11, 0x78, 0x91, 0x97, 0xcc, 0x0a, 0xbf, 0x41, 0xf3, 0x6c, 0x01, 0x72, 0x0d, 0x67,
	0xd2, 0x6d, 0xa2, 0x2c, 0xb1, 0xa5, 0x9f, 0x2c, 0x38, 0x88, 0xbc, 0xc4, 0x2f, 0x4e, 0xb7, 0xf0,
	0x72, 0x40, 0xe3, 0x7b, 0x98, 0x3f, 0x30, 0xc6, 0xab, 0x3d, 0xf9, 0x18, 0x66, 0x2d, 0xdd, 0x94,
	0x83, 0x45, 0xc5, 0xfb, 0x4e, 0xff, 0x3a, 0x9c, 0xb4, 0x74, 0x93, 0xa3, 0x79, 0x1a, 0xa0, 0xf8,
	0x06, 0xce, 0xff, 0x7f, 0x55, 0x82, 0x77, 0x0a, 0x09, 0x81, 0xa3, 0x06, 0x8d, 0x0a, 0xbc, 0xe8,
	0x30, 0xf1, 0x0b, 0x3b, 0xdf, 0x7e, 0x7b, 0x30, 0xc9, 0xd1, 0xac, 0xb0, 0x23, 0x8f, 0x30, 0xdd,
	0x0d, 0x44, 0x42, 0x17, 0x34, 0x1d, 0x49, 0x19, 0x5e, 0xa4, 0xae, 0x9a, 0xf4, 0xaf, 0x9a, 0x74,
	0x39, 0x54, 0x43, 0x56, 0x30, 0xdd, 0xb5, 0xde, 0x6a, 0x8c, 0x44, 0x09, 0x17, 0xa3, 0x9c, 0xbb,
	0x75, 0x3d, 0xb1, 0xdc, 0xdd, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf8, 0x10, 0x7f, 0x92, 0xab,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// KeyGenClient is the client API for KeyGen service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type KeyGenClient interface {
	PopulateKeys(ctx context.Context, in *PopulateKeysRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	AllocateKeys(ctx context.Context, in *AllocateKeysRequest, opts ...grpc.CallOption) (*AllocateKeysResponse, error)
}

type keyGenClient struct {
	cc *grpc.ClientConn
}

func NewKeyGenClient(cc *grpc.ClientConn) KeyGenClient {
	return &keyGenClient{cc}
}

func (c *keyGenClient) PopulateKeys(ctx context.Context, in *PopulateKeysRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/proto.KeyGen/PopulateKeys", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyGenClient) AllocateKeys(ctx context.Context, in *AllocateKeysRequest, opts ...grpc.CallOption) (*AllocateKeysResponse, error) {
	out := new(AllocateKeysResponse)
	err := c.cc.Invoke(ctx, "/proto.KeyGen/AllocateKeys", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KeyGenServer is the server API for KeyGen service.
type KeyGenServer interface {
	PopulateKeys(context.Context, *PopulateKeysRequest) (*empty.Empty, error)
	AllocateKeys(context.Context, *AllocateKeysRequest) (*AllocateKeysResponse, error)
}

// UnimplementedKeyGenServer can be embedded to have forward compatible implementations.
type UnimplementedKeyGenServer struct {
}

func (*UnimplementedKeyGenServer) PopulateKeys(ctx context.Context, req *PopulateKeysRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PopulateKeys not implemented")
}
func (*UnimplementedKeyGenServer) AllocateKeys(ctx context.Context, req *AllocateKeysRequest) (*AllocateKeysResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllocateKeys not implemented")
}

func RegisterKeyGenServer(s *grpc.Server, srv KeyGenServer) {
	s.RegisterService(&_KeyGen_serviceDesc, srv)
}

func _KeyGen_PopulateKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PopulateKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyGenServer).PopulateKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.KeyGen/PopulateKeys",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyGenServer).PopulateKeys(ctx, req.(*PopulateKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyGen_AllocateKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllocateKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyGenServer).AllocateKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.KeyGen/AllocateKeys",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyGenServer).AllocateKeys(ctx, req.(*AllocateKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _KeyGen_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.KeyGen",
	HandlerType: (*KeyGenServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PopulateKeys",
			Handler:    _KeyGen_PopulateKeys_Handler,
		},
		{
			MethodName: "AllocateKeys",
			Handler:    _KeyGen_AllocateKeys_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/adapter/rpc/proto/kgs.proto",
}
